sudo: required

services:
  - docker

script:
  - docker build -t danidalle/sbt-docker-build .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push  danidalle/sbt-docker-build;
    fi
